name: "hire"
version: "1.0.0"

profile: "project_HiRe"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  hire:
    +materialized: view

    src:
      +materialized: ephemeral

    dim:
      +schema: refined

    fct:
      +schema: refined

    marts:
      +schema: marts
